#!/usr/bin/env python3
"""
Universal LLM API Response Extractor
====================================

Extracts the actual text generated by an LLM from a provider's API response.
Handles the fact that different providers return the LLM's text in different
locations within their JSON response structure.

This module is the companion to llm_parser.py:
    - llm_parser.py:              LLM text  → valid Python object
    - llms_response_extractor.py: API JSON  → LLM text

Design Principles (from OpenAI, Anthropic, Cloudflare docs & academic literature):
    1. Separate envelope unwrapping from content extraction
    2. Be content-agnostic (don't judge whether text is JSON, prose, etc.)
    3. Detect error envelopes explicitly before extraction
    4. Learn successful extraction paths per provider/model
    5. Provide rich diagnostics on failure

Supported Providers:
    - Cloudflare Workers AI (native + OpenAI-compatible)
    - OpenAI / Azure OpenAI / Groq (OpenAI-compatible)
    - Anthropic Claude
    - Google Gemini
    - Mistral AI
    - Generic / unknown providers (recursive fallback)

Usage:
    from llms_response_extractor import LLMResponseExtractor
    
    extractor = LLMResponseExtractor()
    text = extractor.extract(
        api_response,
        provider="cloudflare",
        model="@cf/meta/llama-3.1-8b-instruct",
    )

Author: Automated Scientific Pipeline
License: MIT
"""

from typing import Any, Dict, List, Optional, Tuple, Union


class LLMResponseExtractionError(Exception):
    """Raised when text cannot be extracted from an API response."""
    
    def __init__(
        self,
        message: str,
        response_preview: str = "",
        candidates: List[str] = None,
        provider: str = "",
        model: str = "",
    ):
        self.message = message
        self.response_preview = response_preview
        self.candidates = candidates or []
        self.provider = provider
        self.model = model
        super().__init__(message)
    
    def __str__(self):
        parts = [self.message]
        if self.provider:
            parts.append(f"provider={self.provider}")
        if self.model:
            parts.append(f"model={self.model}")
        if self.candidates:
            parts.append(f"candidates_found={len(self.candidates)}")
        if self.response_preview:
            parts.append(f"preview={self.response_preview[:200]}")
        return " | ".join(parts)


class LLMResponseExtractor:
    """
    Extracts LLM-generated text from provider API responses.
    
    Architecture (layered, per OpenAI/Anthropic/Cloudflare patterns):
    
        ┌─────────────────────────────────────────┐
        │  Layer 1: Envelope Validation            │
        │  - Check for error responses             │
        │  - Verify response structure             │
        ├─────────────────────────────────────────┤
        │  Layer 2: Content Location               │
        │  - Known provider patterns (fast)        │
        │  - Generic field search (medium)         │
        │  - Recursive search + scoring (fallback) │
        ├─────────────────────────────────────────┤
        │  Layer 3: Content Extraction             │
        │  - Extract string from located position  │
        │  - Handle nested content structures      │
        ├─────────────────────────────────────────┤
        │  Layer 4: Adaptive Learning              │
        │  - Remember successful paths             │
        │  - Track statistics                      │
        └─────────────────────────────────────────┘
    
    Example:
        >>> extractor = LLMResponseExtractor()
        >>> response = {"result": {"response": "Hello world"}}
        >>> extractor.extract(response, provider="cloudflare")
        'Hello world'
    """
    
    # ------------------------------------------------------------------
    # Known response patterns for common providers
    # Each pattern: (path, description)
    # Path is a list of keys (str) or indices (int) to traverse
    # ------------------------------------------------------------------
    KNOWN_PATTERNS: Dict[str, List[Tuple[List, str]]] = {
        # OpenAI / Groq / Azure / Together AI / OpenRouter
        "openai": [
            (["choices", 0, "message", "content"], "OpenAI chat completion"),
            (["choices", 0, "text"], "OpenAI text completion"),
            (["choices", 0, "delta", "content"], "OpenAI streaming delta"),
        ],
        # Anthropic Claude
        "anthropic": [
            (["content", 0, "text"], "Anthropic Claude 3+"),
        ],
        # Google Gemini
        "gemini": [
            (["candidates", 0, "content", "parts", 0, "text"], "Gemini"),
        ],
        # Cloudflare Workers AI (multiple formats observed)
        "cloudflare": [
            (["result", "response"], "Cloudflare native (string)"),
            (["result", "response", "content"], "Cloudflare native (dict)"),
            (["result", "message", "content"], "Cloudflare OpenAI-compat"),
            (["result", "choices", 0, "message", "content"], "Cloudflare OpenAI-compat alt"),
        ],
        # Mistral
        "mistral": [
            (["choices", 0, "message", "content"], "Mistral chat"),
        ],
    }
    
    # Field names that commonly contain the LLM text
    # NOTE: Excluded "message" and "result" as they are usually wrapper objects
    GENERIC_FIELD_NAMES = {
        "content", "response", "text", "output", "completion",
        "answer", "reply", "generated_text", "generated",
    }
    
    # Error indicators in API responses
    ERROR_INDICATORS = {
        "error", "errors", "err", "fault", "failure",
    }
    
    def __init__(self, verbose: bool = False):
        """
        Initialize the extractor.
        
        Args:
            verbose: If True, print debug information to stderr
        """
        self.verbose = verbose
        # Track successful extraction paths: {(provider, model): [path, ...]}
        self.successful_paths: Dict[Tuple[str, str], List[List]] = {}
        # Stats: {(provider, model, strategy): count}
        self.stats: Dict[str, int] = {}
    
    def _log(self, message: str):
        if self.verbose:
            import sys
            print(f"  [Extractor] {message}", file=sys.stderr)
    
    # ================================================================
    # LAYER 1: ENVELOPE VALIDATION
    # ================================================================
    
    def _check_for_errors(self, response: Any) -> Optional[str]:
        """
        Check if the response is an error envelope.
        
        Cloudflare error format:
            {"success": false, "errors": [{"code": 10000, "message": "..."}]}
        
        OpenAI error format:
            {"error": {"message": "...", "type": "...", "code": "..."}}
        
        Returns:
            Error message if this is an error response, None otherwise
        """
        if not isinstance(response, dict):
            return None
        
        # Cloudflare-style error
        if response.get("success") is False:
            errors = response.get("errors", [])
            if isinstance(errors, list) and errors:
                first_error = errors[0]
                if isinstance(first_error, dict):
                    return f"API error {first_error.get('code', '?')}: {first_error.get('message', 'Unknown error')}"
                return f"API error: {first_error}"
            return "API returned success=false with no error details"
        
        # OpenAI-style error
        if "error" in response:
            error_val = response["error"]
            if isinstance(error_val, dict):
                return f"API error: {error_val.get('message', str(error_val))}"
            return f"API error: {error_val}"
        
        # Generic error fields
        for key in self.ERROR_INDICATORS:
            if key in response and response[key]:
                error_val = response[key]
                if isinstance(error_val, str):
                    return f"API error ({key}): {error_val}"
                elif isinstance(error_val, dict):
                    return f"API error ({key}): {error_val.get('message', str(error_val))}"
        
        return None
    
    def _validate_response_type(self, response: Any) -> Optional[str]:
        """
        Validate that the response is a type we can work with.
        
        Returns:
            Error message if invalid, None if valid
        """
        if response is None:
            return "Response is None"
        if isinstance(response, str):
            return None  # Strings are valid (some providers return raw text)
        if isinstance(response, (dict, list)):
            return None
        return f"Response is not a dict/list/string, got {type(response).__name__}"
    
    # ================================================================
    # LAYER 2: CONTENT LOCATION
    # ================================================================
    
    def _traverse(self, response: Any, path: List) -> Optional[str]:
        """
        Safely traverse a nested structure following a path.
        
        Args:
            response: The response dict/list to traverse
            path: List of keys (str) or indices (int) to follow
            
        Returns:
            The value at the end of the path if it's a string, else None
        """
        current = response
        for step in path:
            try:
                if isinstance(step, int):
                    if isinstance(current, (list, tuple)) and 0 <= step < len(current):
                        current = current[step]
                    else:
                        return None
                else:
                    if isinstance(current, dict) and step in current:
                        current = current[step]
                    else:
                        return None
            except (KeyError, IndexError, TypeError):
                return None
        
        # Return the value if it's a string
        if isinstance(current, str):
            return current
        return None
    
    def _try_known_patterns(
        self, response: Any, provider: str, model: str
    ) -> Optional[str]:
        """
        Try provider-specific known response paths.
        
        This is the fastest strategy and most accurate when we know
        the provider. We also try previously successful paths first.
        """
        provider_lower = (provider or "").lower()
        
        # First, try paths that previously worked for this provider/model
        key = (provider_lower, model)
        if key in self.successful_paths:
            for path in self.successful_paths[key]:
                result = self._traverse(response, path)
                if result and result.strip():
                    self._log(f"Known path worked: {path}")
                    return result
        
        # Then try all known patterns for this provider
        patterns = self.KNOWN_PATTERNS.get(provider_lower, [])
        for path, description in patterns:
            result = self._traverse(response, path)
            if result and result.strip():
                self._log(f"Known pattern matched: {description}")
                self._remember_path(provider_lower, model, path)
                return result
        
        # If provider not in our known list, try ALL known patterns
        for p, patterns in self.KNOWN_PATTERNS.items():
            for path, description in patterns:
                result = self._traverse(response, path)
                if result and result.strip():
                    self._log(f"Cross-provider pattern matched: {description}")
                    return result
        
        return None
    
    def _try_generic_fields(self, response: Any) -> Optional[str]:
        """
        Look for common field names that contain strings.
        
        This handles providers we haven't seen before or when the
        response format has changed.
        """
        candidates = []
        self._collect_strings_at_known_keys(response, candidates, depth=0, max_depth=5)
        
        if not candidates:
            return None
        
        # Sort by length (longest first - more likely to be the full LLM output)
        candidates.sort(key=len, reverse=True)
        
        for candidate in candidates[:3]:  # Top 3 by length
            if self._looks_like_text(candidate):
                self._log(f"Generic field matched (length {len(candidate)})")
                return candidate
        
        return candidates[0] if candidates else None
    
    def _collect_strings_at_known_keys(
        self, obj: Any, candidates: List[str], depth: int, max_depth: int
    ):
        """Recursively find string values at known field names."""
        if depth > max_depth:
            return
        
        if isinstance(obj, dict):
            for key, value in obj.items():
                if isinstance(key, str) and key.lower() in self.GENERIC_FIELD_NAMES:
                    if isinstance(value, str) and value.strip():
                        candidates.append(value)
                    elif isinstance(value, dict):
                        # Handle nested content: {"content": {"text": "..."}}
                        for sub_key in ["text", "value", "data"]:
                            if sub_key in value and isinstance(value[sub_key], str):
                                candidates.append(value[sub_key])
                # Recurse into nested structures
                self._collect_strings_at_known_keys(value, candidates, depth + 1, max_depth)
        elif isinstance(obj, (list, tuple)):
            for item in obj:
                self._collect_strings_at_known_keys(item, candidates, depth + 1, max_depth)
    
    def _try_recursive_search(self, response: Any) -> Optional[str]:
        """
        Find ALL string values in the response and score them.
        
        This is the most general strategy - it works even when the
        response structure is completely unknown.
        
        IMPORTANT: This method is content-agnostic. It does NOT penalize
        JSON strings, because our pipeline expects JSON output from the LLM.
        """
        all_strings = []
        self._collect_all_strings(response, all_strings, depth=0, max_depth=10)
        
        if not all_strings:
            return None
        
        # Score each string by "text-likeness" (content-agnostic)
        scored = [(self._score_text_likeness(s), s) for s in all_strings if s.strip()]
        scored.sort(key=lambda x: x[0], reverse=True)
        
        if not scored:
            return None
        
        best_score, best_string = scored[0]
        self._log(f"Recursive search: best score {best_score:.2f} for string of length {len(best_string)}")
        
        # Only return if the score is reasonable
        if best_score > 0.2:
            return best_string
        
        return None
    
    def _collect_all_strings(
        self, obj: Any, collector: List[str], depth: int, max_depth: int
    ):
        """Recursively collect all string values from a nested structure."""
        if depth > max_depth:
            return
        
        if isinstance(obj, str):
            # Only collect non-trivial strings
            if len(obj) > 5:
                collector.append(obj)
        elif isinstance(obj, dict):
            for value in obj.values():
                self._collect_all_strings(value, collector, depth + 1, max_depth)
        elif isinstance(obj, (list, tuple)):
            for item in obj:
                self._collect_all_strings(item, collector, depth + 1, max_depth)
    
    # ================================================================
    # LAYER 3: CONTENT SCORING
    # ================================================================
    
    def _score_text_likeness(self, text: str) -> float:
        """
        Score how likely a string is to be actual LLM-generated content.
        
        IMPORTANT: This method is CONTENT-AGNOSTIC. It does NOT penalize
        JSON strings, because our pipeline expects JSON output from the LLM.
        It only scores based on structural properties:
        - Length (longer = more likely to be full output)
        - Presence of words/sentences
        - NOT a URL, ID, or very short string
        
        Returns:
            Score between 0.0 and 1.0
        """
        if not text or len(text) < 10:
            return 0.0
        
        score = 0.0
        
        # Length factor (longer = more likely to be full LLM output)
        length_score = min(0.7, len(text) / 3000.0)
        score += length_score
        
        # Word density (LLM text has many words)
        words = text.split()
        if len(words) >= 3:
            score += 0.1
        
        # Sentence or structure indicators
        sentence_markers = sum(1 for c in text if c in ".!?")
        if sentence_markers >= 1:
            score += 0.05
        
        # Penalize URLs and IDs (these are metadata, not LLM output)
        stripped = text.strip()
        if stripped.startswith("http") or "://" in stripped[:20]:
            score *= 0.2
        
        # Penalize very short strings (likely keys or field names)
        if len(text) < 20:
            score *= 0.5
        
        return min(1.0, score)
    
    def _looks_like_text(self, text: str) -> bool:
        """Quick check if a string looks like LLM-generated content."""
        if not text or len(text) < 10:
            return False
        return self._score_text_likeness(text) > 0.2
    
    # ================================================================
    # LAYER 4: ADAPTIVE LEARNING
    # ================================================================
    
    def _remember_path(self, provider: str, model: str, path: List):
        """Remember a successful extraction path."""
        key = (provider, model)
        if key not in self.successful_paths:
            self.successful_paths[key] = []
        if path not in self.successful_paths[key]:
            self.successful_paths[key].append(path)
    
    def _record_success(self, provider: str, model: str, strategy: str):
        """Record a successful extraction for stats tracking."""
        key = f"{provider}:{model}:{strategy}"
        self.stats[key] = self.stats.get(key, 0) + 1
    
    # ================================================================
    # MAIN EXTRACTION METHOD
    # ================================================================
    
    def extract(
        self,
        response: Any,
        provider: str = "unknown",
        model: str = "unknown",
        raise_on_failure: bool = True,
    ) -> Optional[str]:
        """
        Extract the LLM-generated text from an API response.
        
        This is the main entry point. It applies a layered approach:
        
        1. Validate the response type
        2. Check for error envelopes
        3. Try known provider patterns (fast)
        4. Try generic field search (medium)
        5. Try recursive search with scoring (fallback)
        
        Args:
            response: The API response (dict, list, or string)
            provider: Provider name (cloudflare, openai, anthropic, etc.)
            model: Model name (for adaptive learning)
            raise_on_failure: If True, raise exception; if False, return None
            
        Returns:
            The extracted LLM text, or None if extraction failed
            
        Raises:
            LLMResponseExtractionError: If all strategies fail and raise_on_failure=True
            
        Example:
            >>> extractor = LLMResponseExtractor()
            >>> response = {"result": {"response": "Hello world"}}
            >>> extractor.extract(response, provider="cloudflare")
            'Hello world'
        """
        # Layer 1a: Validate response type
        type_error = self._validate_response_type(response)
        if type_error:
            if raise_on_failure:
                raise LLMResponseExtractionError(
                    type_error,
                    response_preview=str(response)[:200],
                    provider=provider,
                    model=model,
                )
            return None
        
        # Handle already-string input (some providers return raw text)
        if isinstance(response, str):
            self._record_success(provider, model, "direct_string")
            return response
        
        # Layer 1b: Check for error envelopes
        error_message = self._check_for_errors(response)
        if error_message:
            if raise_on_failure:
                raise LLMResponseExtractionError(
                    error_message,
                    response_preview=str(response)[:500],
                    provider=provider,
                    model=model,
                )
            return None
        
        # Layer 2: Try extraction strategies in order
        strategies = [
            ("known_patterns", lambda: self._try_known_patterns(response, provider, model)),
            ("generic_fields", lambda: self._try_generic_fields(response)),
            ("recursive_search", lambda: self._try_recursive_search(response)),
        ]
        
        for strategy_name, strategy_func in strategies:
            try:
                result = strategy_func()
                if result and result.strip():
                    self._log(f"Success with strategy: {strategy_name}")
                    self._record_success(provider, model, strategy_name)
                    return result
            except Exception as e:
                self._log(f"Strategy {strategy_name} raised exception: {e}")
                continue
        
        # All strategies failed
        if raise_on_failure:
            all_strings = []
            self._collect_all_strings(response, all_strings, depth=0, max_depth=5)
            raise LLMResponseExtractionError(
                "Could not extract LLM text from response",
                response_preview=str(response)[:500],
                candidates=[s[:100] for s in all_strings[:10]],
                provider=provider,
                model=model,
            )
        return None
    
    def get_stats(self) -> Dict[str, int]:
        """Return extraction statistics."""
        return dict(self.stats)
    
    def get_learned_paths(self) -> Dict[str, List[List]]:
        """Return the paths learned to work for each provider/model."""
        return {
            f"{provider}:{model}": paths
            for (provider, model), paths in self.successful_paths.items()
        }


# ============================================================
# CONVENIENCE FUNCTION
# ============================================================

def extract_llm_text(
    response: Any,
    provider: str = "unknown",
    model: str = "unknown",
    verbose: bool = False,
) -> Optional[str]:
    """
    Quick convenience function to extract LLM text from an API response.
    
    Example:
        >>> from llms_response_extractor import extract_llm_text
        >>> text = extract_llm_text(api_response, provider="cloudflare")
    """
    extractor = LLMResponseExtractor(verbose=verbose)
    return extractor.extract(response, provider=provider, model=model)
