from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path("audit_engine/semantic_audit/high_assurance")


def imported_roots(path: Path):
    tree = ast.parse(path.read_text(encoding="utf-8"))
    roots = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            roots.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            roots.add(node.module.split(".")[0])
    return roots


def test_high_assurance_layer_does_not_import_findings_rules_memory_or_promotion():
    forbidden_fragments = (
        "semantic_audit.findings", "semantic_audit.rules", "semantic_audit.evolution.memory",
        "semantic_audit.promotion",
    )
    for path in ROOT.glob("*.py"):
        text = path.read_text(encoding="utf-8")
        assert not any(fragment in text for fragment in forbidden_fragments), path


def test_controlled_executor_has_no_shell_or_network_execution_api():
    path = ROOT / "execution.py"
    tree = ast.parse(path.read_text(encoding="utf-8"))
    roots = imported_roots(path)
    assert roots.isdisjoint({"subprocess", "socket", "requests", "urllib"})
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            if isinstance(node.func.value, ast.Name):
                assert (node.func.value.id, node.func.attr) != ("os", "system")


def test_high_assurance_layer_does_not_activate_formal_package():
    for path in ROOT.glob("*.py"):
        assert "from formal" not in path.read_text(encoding="utf-8")
        assert "import formal" not in path.read_text(encoding="utf-8")


def test_formal_router_remains_inactive():
    from formal.router import FormalRouter
    try:
        FormalRouter().route("existence", 1.0, 0.5)
    except NotImplementedError:
        pass
    else:
        raise AssertionError("G3.4.0 must not silently activate the placeholder formal router.")


def test_g3_workflows_05_through_14_are_manual_only_after_patch_generation():
    # Workflow 14 is generated by this milestone; this assertion intentionally
    # fails until the governance file exists, catching accidental trigger drift.
    workflow_dir = Path(".github/workflows")
    for n in range(5, 15):
        matches = list(workflow_dir.glob(f"{n:02d}_*.yml"))
        assert len(matches) == 1, n
        text = matches[0].read_text(encoding="utf-8")
        assert "on:\n  workflow_dispatch:\n" in text
        assert "\n  push:" not in text
        assert "\n  pull_request:" not in text
